### ISSUE TITLE
post job stack on spinner

### ISSUE THREAD

**Issue by lironmo** [manjurulhoque/react-job-portal#4]
Hi,
it seems that there is an assumption about the tags prior to the job (pre-defined tags that need to be stored in the database before the form is rendered).

probably need to add in the readme or remove dependency (create tags on the fly)

![image](https://user-images.githubusercontent.com/37513762/150777701-a822bff3-f0d8-40ce-b0b9-a5798297e33c.png)

**Comment by lironmo** [comment]
` tags?.length > 0 && (`

**Comment by manjurulhoque** [comment]
Fixed
